/**
 * PDF 合成：把各方签名图嵌入到初稿 PDF 上，再追加一页"电子签约审计页"。
 *
 * 用 pdf-lib（不是 pdfkit），因为 pdf-lib 适合"加载已有 PDF + 叠加"，
 * pdfkit 适合"从零生成"。
 *
 * 关于 PDF 哈希：
 *   依据《电子签名法》第 13 条第 (3)(4) 项，"签名后改动可发现"通过
 *   contracts.pdf_hash_sha256 字段实现（外部存哈希），不在 PDF 内部写哈希
 *   （否则有"先有鸡还是先有蛋"问题：算哈希前需要先写 placeholder，
 *   写完后哈希又变了）。
 */

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { SignerRole } from "@/types/contract";

export interface SignerAuditInfo {
  role: SignerRole;
  name: string;
  phone: string;
  signed_at: string;                  // ISO 8601
  sign_ip: string | null;
  sign_ua: string | null;
  sms_verified_at: string | null;
  /** 已下载的签名 PNG buffer；用于嵌入签字页 */
  signature_png?: Buffer;
}

const ROLE_LABEL: Record<SignerRole, string> = {
  landlord: "Landlord",
  agent: "Agent",
  tenant: "Tenant",
};

/**
 * 合成最终 PDF：
 *   1. 在初稿 PDF 最后一页（签字页）的预留签字框上贴签名图
 *   2. 追加一页审计页，包含所有签字方的姓名/手机（脱敏）/时间/IP/UA/验证码确认时间
 *
 * 返回最终 PDF 的 Buffer，由调用方计算 SHA256 后入库。
 */
export async function composeFinalPdf(opts: {
  initialPdf: Buffer;
  signers: SignerAuditInfo[];
  contractId: string;
}): Promise<Buffer> {
  const src = await PDFDocument.load(opts.initialPdf);

  // ===== 1. 在签字页贴签名图 =====
  // 签字页在初稿 PDF 的最后一页（direct 模板用 addPage 单独一页）
  const lastPage = src.getPage(src.getPageCount() - 1);
  const { height: pageH } = lastPage.getSize();

  // 签字框 Y 坐标按 direct 模板预留位置估算：
  // 标题 "签字页" 在顶部，往下两个签字框（约 80pt 高），相隔 ~120pt
  const signatureSlots: Record<SignerRole, { x: number; y: number; w: number; h: number }> = {
    landlord: { x: 200, y: pageH - 180, w: 180, h: 50 },
    agent:    { x: 200, y: pageH - 320, w: 180, h: 50 },
    tenant:   { x: 200, y: pageH - 460, w: 180, h: 50 },
  };

  for (const s of opts.signers) {
    if (!s.signature_png) continue;
    const slot = signatureSlots[s.role];
    if (!slot) continue;
    // 直租只有 2 方时，租客槽应紧挨房东下方而不是跳过中介槽：
    const effectiveSlot =
      opts.signers.length === 2 && s.role === "tenant"
        ? signatureSlots.agent          // 直租：租客占用 agent 的位置
        : slot;
    try {
      const img = await src.embedPng(s.signature_png);
      // 按签字框大小缩放，保持纵横比
      const scale = Math.min(effectiveSlot.w / img.width, effectiveSlot.h / img.height);
      const drawW = img.width * scale;
      const drawH = img.height * scale;
      lastPage.drawImage(img, {
        x: effectiveSlot.x,
        y: effectiveSlot.y,
        width: drawW,
        height: drawH,
      });
    } catch (err) {
      console.error("[pdf-composer] embed signature failed:", s.role, err);
    }
  }

  // ===== 2. 追加审计页 =====
  const auditPage = src.addPage();
  const font = await src.embedFont(StandardFonts.Helvetica);
  const fontBold = await src.embedFont(StandardFonts.HelveticaBold);

  // 审计页用 Latin-only 字符（避免依赖中文字体）：title + 字段标签英文 + 数据原样
  let y = auditPage.getHeight() - 60;
  const drawLine = (
    txt: string,
    opt: { size?: number; bold?: boolean; color?: [number, number, number] } = {}
  ) => {
    const size = opt.size ?? 10;
    auditPage.drawText(txt, {
      x: 50,
      y,
      size,
      font: opt.bold ? fontBold : font,
      color: rgb(...(opt.color ?? [0, 0, 0])),
    });
    y -= size + 4;
  };

  drawLine("Electronic Signature Audit", { size: 16, bold: true });
  drawLine("Generated by yangfang Tend / Tend - 1 / yfn", { size: 8, color: [0.4, 0.4, 0.4] });
  y -= 12;
  drawLine(`Contract ID: ${opts.contractId}`, { size: 10 });
  drawLine(`Final PDF generated at: ${new Date().toISOString()}`, { size: 10 });
  y -= 8;

  drawLine("Signers:", { size: 12, bold: true });
  y -= 2;
  for (const s of opts.signers) {
    const phoneMask = maskPhone(s.phone);
    const ipMask = maskIp(s.sign_ip);
    drawLine(`[${ROLE_LABEL[s.role]}]  ${maskAscii(s.name)}  ${phoneMask}`, { bold: true });
    drawLine(`  Signed at: ${s.signed_at}`);
    drawLine(`  IP: ${ipMask}`);
    drawLine(`  User-Agent: ${(s.sign_ua ?? "").slice(0, 80)}`);
    drawLine(`  SMS verified at: ${s.sms_verified_at ?? "-"}`);
    y -= 6;
  }

  y -= 8;
  drawLine("Legal Basis:", { size: 12, bold: true });
  drawLine("Article 13 & 14, Electronic Signature Law of the PRC (2019 amendment):");
  drawLine("A reliable electronic signature has the same legal effect as a handwritten signature.");
  y -= 8;
  drawLine("Custodian: Tend platform (Shenzhen Yikai Technology Co., Ltd.)", {
    size: 9,
    color: [0.4, 0.4, 0.4],
  });
  drawLine("Audit log retention: at least 5 years.", { size: 9, color: [0.4, 0.4, 0.4] });
  drawLine("Chinese contract text precedes this English audit page; in case of conflict, the", {
    size: 8,
    color: [0.4, 0.4, 0.4],
  });
  drawLine("Chinese contract prevails.", { size: 8, color: [0.4, 0.4, 0.4] });

  const bytes = await src.save();
  return Buffer.from(bytes);
}

// ============================================================
// 工具
// ============================================================

function maskPhone(p: string): string {
  if (!p || p.length < 7) return p ?? "-";
  return p.slice(0, 3) + "****" + p.slice(-4);
}

function maskIp(ip: string | null): string {
  if (!ip) return "-";
  const parts = ip.split(".");
  if (parts.length !== 4) return ip;
  return `${parts[0]}.${parts[1]}.${parts[2]}.***`;
}

/** pdf-lib 的 StandardFonts 不支持中文，姓名用脱敏后只保留 ASCII 的形式（不是中文展示）*/
function maskAscii(s: string): string {
  // 把每个非 ASCII 字符换成 * 保护隐私，同时避免渲染失败
  return s.replace(/[^\x20-\x7E]/g, "*");
}
